vol_time_defaults:
  vol_window_minutes: 240
  nearest_tolerance_seconds: 60
  timebar_freq: 1T
  source:
    kind: ticks
    ticks_glob: data/ticks_raw/*2025-0[1-7]*.csv
    timebars_glob: data/timebars_1m/*.parquet
labeling:
  use_ohlc: true
  allow_same_bar_touch: true
  same_bar_resolution: drop
  normalize_by_close: false
  horizon:
    type: clock
    minutes: 240
  max_holding_bars: 5000
  vol_method: atr
  atr_kind: wilder
  atr_period: 14
  barriers:
    mode: atr
    pt_mult: 1.25
    sl_mult: 1.25
  label_classes:
  - 1
  - 0
  - -1
